In [2]:
import numpy as np
import numpy.random as rng


In [14]:
def parity_check_matrix(n_code, d_v, d_c):

    n_equations = (n_code * d_v) // d_c

    block = np.zeros((n_equations // d_v, n_code), dtype=int)
    H = np.empty((n_equations, n_code))
    block_size = n_equations // d_v

    # Filling the first block with consecutive ones in each row of the block
    for i in range(block_size):
        for j in range(i * d_c, (i + 1) * d_c):
            block[i, j] = 1
    H[:block_size] = block

    # Create remaining blocks by shuffling the first block's columns
    for i in range(1, d_v):
        perm = np.arange(n_code)
        np.random.shuffle(perm)
        H[i * block_size: (i + 1) * block_size] = block[:, perm]
    H = H.astype(int)
    return matrix(H)

In [4]:
def check_distinct_columns(matrix):
    num_columns = matrix.ncols()
    for i in range(num_columns - 1):
        for j in range(i + 1, num_columns):
            if matrix.column(i) == matrix.column(j):
                return False
    return True

In [5]:
# Set the desired parameters
n_code = 20  # Number of code bits
d_v = 3  # Variable node degree
d_c = 5  # Check node degree

# Generate the parity check matrix
H = parity_check_matrix(n_code, d_v, d_c)
while not check_distinct_columns(H):
    H = parity_check_matrix(n_code, d_v, d_c) 

# Print the resulting parity check matrix
print(H)

H.dimensions()

[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
[1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 1 0 1]
[0 0 1 0 1 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 1 0 1 1 1 0 0 0 0 0 0 1 0]
[0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 1]
[1 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0]
[0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0]
[0 0 0 0 1 0 0 0 0 1 0 1 1 0 1 0 0 0 0 0]


(12, 20)

In [6]:
def generate_H(n, d_v, d_c, seed=None): 
    rnd = np.random.RandomState(131) 
    # Compute the number of columns and m is equal to the number of check bit
    m = (n * d_v) // d_c

    # Compute the basic matrix H0
    Set = np.zeros((m//d_v, n), dtype=int)
    a = m // d_v

    # Filling the first set with consecutive ones in each row of the set
    for i in range(a):
        for j in range(i * d_c, (i+1)* d_c):
            Set[i, j] = 1
    # Create list of Sets and append the first reference set
    Sets = []
    Sets.append(Set.tolist())
    permutations = [] # List to store permutations 
    
    # reate remaining sets by permutations of the first set's columns:
    for i in range(1, d_v):
        newSet = rnd.permutation(np.transpose(Set)).T.tolist()
        Sets.append(newSet)
        permutations.append(np.where(np.transpose(Set) != np.transpose(newSet))[1].tolist())
    # Returns concatenated list of sest:
    H = np.concatenate(Sets)
    print(permutations)
    return matrix(H)


In [10]:
N = 20 
Wc = 3 
Wr = 5 
H = generate_H(N, Wc, Wr) 
H

[[0, 2, 0, 1, 0, 1, 0, 3, 1, 3, 1, 3, 0, 1, 1, 3, 0, 1, 1, 2, 0, 2, 0, 2, 1, 2, 2, 3, 2, 3, 1, 3, 2, 3], [0, 3, 0, 1, 0, 2, 1, 2, 1, 3, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 0, 2, 2, 3, 0, 3, 2, 3, 0, 3]]


[1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1]
[0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0]
[0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0]
[0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1]
[0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
[0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0]

In [22]:
H.dimensions() 
# Note H0 is of dim. (4, 20) 
H[4:]

[0 0 0 0 1 0 0 1 0 1 0 1 1 0 0 0 0 0 0 0]
[0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 1 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0]
[0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1]
[0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 0]
[0 0 1 0 0 0 1 0 1 1 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 1 0]

In [13]:
# Construct the sets N(m) and M(n) for the previously found parity check matrix H, 
# and construct the Tannner graph for H. 

N_m = [[i for i, e in enumerate(row) if e == 1] for row in H]
M_n = [[i for i, e in enumerate(column) if e == 1] for column in H.columns()]
